---
title: 'Reproducibility in Data Science'
author: "Jessica Minnier, PhD<br><span style = 'font-size: 50%;'>Assistant Professor of Biostatistics<br>OHSU-PSU School of Public Health<br>Knight Cancer Institute Biostatistics Shared Resource<br>Oregon Health & Science University</span>"
date: 'HIP 523 Computerized Data Management<br><br>`r icon::fa("link")` [bit.ly/hip-repro](https://bit.ly/jmin-jsm19)<br>`r icon::fa("twitter")` [datapointier](https://twitter.com/datapointier)'
output:
  xaringan::moon_reader:
    css: [css/xaringan-themer.css, css/my-theme.css]
    lib_dir: libs
    nature:
      countIncrementalSlides: false
      titleSlideClass: ["left", "middle", "inverse"]
      highlightLines: true
      highlightStyle: solarized-dark
      ratio: "16:9"
    includes:
      in_header: ../libs/header.html
---

layout: true


---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

library(tidyverse)

knitr::opts_chunk$set(
  warning=FALSE, 
  message=FALSE, 
  fig.width=10.5, 
  fig.height=4, 
  comment=NA, 
  rows.print=16,
  echo=FALSE)
theme_set(theme_bw(base_size = 24))
```


```{r xaringan-themer, include = FALSE}
# devtools::install_github("gadenbuie/xaringanthemer")
library(xaringanthemer)
mono_light(
  base_color =  "#3A6185", #5e97c9" ## OHSU Marquam, #"#125972" ## picked to coordinate with rOpenSci logo 
  code_highlight_color = "#c0e8f5",
  link_color = "#38BDDE",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Droid Mono"),
  text_font_size = "26px",
  outfile = "css/xaringan-themer.css"
  # title_slide_background_image = "img/CAN-RGB-4C-REV.png",
  # title_slide_background_position = "80% 60%",
  # title_slide_background_size = "400px" #"40%"
)
```


class: inverse, middle

# Who am I?

- Use R every day, git often, unix sometimes, python rarely
- Teach intro to R, R markdown, intro to stats for data science, R Shiny (and Math/Stats)
- Collaborative statistician (mostly applied work, no PhD students, no Postdocs, some MS students and staff)
- Involved in: organizing Cascadia R conf, PDX R Meetup, R Ladies, BioData Club

---